### ISSUE TITLE
Crash: 553 Color Palette with client 2014-10-22

### ISSUE THREAD

**Issue by OscarScorp** [MStr3am/NEMO#47] opened 2015-07-15 15:46 UTC
I have encountered a crash issue after using the new client 2014-10-22.

Crash when changing color to the new Palettes, but this only happens on some classes such as Kagerou, Rebellion and when a Crusader changes its color while riding a Peco. Without a Peco there is no issue. ¿Does this means the Client does not supports some colors on the Palette? I am unable to select the 'Ignore Missing Palette Error' (Ignore Missing Palette Error: Failed in part 1). Using NEMO.
Crash happens to everyone looking at the user changing to that palette as well.

I am thinking these issues only happen with the new Client, please correct me if I'm wrong.

Thanks in advance.

**Comment by EPuncker** [comment] 2015-07-16 17:40
the issue is that you have missing palettes for those sprites, not really NEMO fault

**Comment by MStr3am** [comment] 2015-07-17 06:38
check is the palette is there. Kagerou and Rebellion are relatively new and maybe some of the palettes are missing.

**Comment by OscarScorp** [comment] 2015-07-17 23:44
The palette error is the following (korean characters won't let me paste it here since I can't find some of the characters): http://gyazo.com/4868981d25428562882e84a56d4dd680

I think I can solve the issue if I duplicate the folder inside palette/ , but I need to find the character which looks like an upwards arrow.

**Comment by MStr3am** [comment] 2015-07-20 06:47
thats not korean its chinese oO   个

**Comment by OscarScorp** [comment] 2015-07-20 12:51
You are right MStr3am, I just realized that... but why is it looking for files in chinese instead of korean?
How can I change this?

**Comment by MStr3am** [comment] 2015-07-22 06:18
hmm not sure but could be your langtype or maybe you're not using a kRO client.
where did u get your client from?

Please post a topic in Herc / rAthena forum so that more people can see the issue.I am closing this since it doesnt seem to be a NEMO issue.

**Closed by MStr3am** 2015-07-22 06:18 UTC
