### ISSUE TITLE
Hotkey Bar  number position

### ISSUE THREAD

**Issue by Emistry** [MStr3am/NEMO#92] opened 2015-12-31 20:52 UTC
Do you think there is a way to fix the position of number display ? 
the position of amount of item displayed seem like lower than the skill's level.

![capture](https://cloud.githubusercontent.com/assets/1075099/12068189/52cda046-b043-11e5-98e0-e081271d32f3.PNG)

**Comment by Emistry** [comment] 2015-12-31 21:01
erm, the position of value or text seem to be lower than before.

i not sure is it related, but chatbox / login interface etc all seem to be having the position lowered.

**Comment by zackdreaver** [comment] 2016-01-03 05:59
I can confirm on client date 2013+
The status window is affected with this issue

**Comment by MStr3am** [comment] 2016-01-05 19:41
![itemcount](https://cloud.githubusercontent.com/assets/4068357/12125601/347e65a8-b412-11e5-8953-91761f49739c.PNG)
OK so I got it to look like this not sure if the count will display wrongly somewhere else because of the patch (I'll keep an Experimental tag).

**Comment by MStr3am** [comment] 2016-01-05 20:11
Have added the patch.Try it out
Move Item Count Upwards.

**Comment by MStr3am** [comment] 2016-01-08 19:51
Please reopen the issue if you face any problems with the patch. Closing for now.

**Closed by MStr3am** 2016-01-08 19:51 UTC
Labels: Completed, New Patch
